name: Rebuild python virtual env

on:
  create:
    tags:
      - v*
  push:
    branches: [ rebuild-venv ]


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/checkout@v1

      - name: prep
        run: sudo mkdir -p /usr/local/inge5/current/
      - name: prep chown
        run: sudo chown `id -u`:`id -g` /usr/local/inge5/current/

      - name: copy project to run location.
        run: cp -r ./event_provider ./requirements.txt /usr/local/inge5/current/

      - name: Create env
        run: python3 -m venv /usr/local/inge5/current/.venv

      - name: pip3 install
        run: cd /usr/local/inge5/current; source .venv/bin/activate; pip install -U pip; pip install -r requirements.txt

      - name: Create archive
        run: tar -czf inge-5_venv_${{ env.RELEASE_VERSION }}.tar.gz /usr/local/inge5/current/.venv

      - name: Upload venv tar
        uses: actions/upload-artifact@v1
        with:
          name: inge-5_venv_${{ env.RELEASE_VERSION }}
          path: inge-5_venv_${{ env.RELEASE_VERSION }}.tar.gz
