name: Create release package

on:
 create:
   tags:
     - v*

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/checkout@v1
      - name: Create tar
        run: tar -czf inge-5_${{ env.RELEASE_VERSION }}.tar.gz ./event_provider ./wsgi.py ./requirements*.txt ./*.sh README.md Makefile
      - name: Upload release tar
        uses: actions/upload-artifact@v1
        with:
          name: inge-5_${{ env.RELEASE_VERSION }}
          path: inge-5_${{ env.RELEASE_VERSION }}.tar.gz
