# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']

jobs:
  code-quality:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Lint with pylint
        run: make lint
      - name: Audit with bandid
        run: make audit
  tests:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make venv
          sudo apt install easy-rsa softhsm2 libsofthsm2 gnutls-bin libengine-pkcs11-openssl php
      - name: Create config
        run: cp inge5.conf.dist inge5.conf
      - name: Create bsn keypair
        run: |
          mkdir -p secrets
          php -r '$keypair = sodium_crypto_box_keypair(); file_put_contents("secrets/bsn_pub.key", base64_encode(sodium_crypto_box_publickey($keypair))); file_put_contents("secrets/bsn.key", base64_encode(sodium_crypto_box_secretkey($keypair)));'
      - name: Create bsn hashkey
        run: |
          tr -dc A-Za-z0-9 </dev/urandom | head -c 20 > secrets/bsn_hash.key
      - name: Create database aes256 key
        run: 
          tr -dc A-Za-z0-9 </dev/urandom | head -c 32 > secrets/db.key
      - name: Test with unittest
        run: make test